=== ror-community/ror-schema/ror_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "ip_addresses": {
      "type": "array",
      "default": []
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "acronyms": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "links": {
      "type": "array",
      "default": [],
      "items": {
        "type": "string"
      }
    },
    "country": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "country_code": {
          "type": "string",
          "minLength": 2,
          "maxLength": 2,
          "readOnly": true
        },
        "country_name": {
          "type": "string",
          "readOnly": true
        }
      },
      "required": ["country_code", "country_name"]
    },
    "name": {
      "$ref": "#/definitions/non-empty-string"
    },
    "wikipedia_url": {
      "type": ["null","string"],
      "default": null

    },
    "addresses": {
      "type": "array",
      "maxItems": 1,
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "geonames_city"
        ],
        "properties": {
          "geonames_city": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "id"
            ],
            "properties": {
              "id": {
                "title": "Location ID",
                "type": "integer"
              },
              "city": {
                "type": "string",
                "readOnly": true
              },
              "license": {
                "type": "object",
                "additionalProperties": false,
                "default": {},
                "properties": {
                  "attribution": {
                    "readOnly": true,
                    "type": "string",
                    "default": "Data from geonames.org under a CC-BY 3.0 license"
                  },
                  "license": {
                    "type": "string",
                    "readOnly": true,
                    "default": "http://creativecommons.org/licenses/by/3.0/"
                  }
                },
                "required": [
                  "attribution",
                  "license"
                ]
              },
              "geonames_admin1": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "ascii_name": {
                    "readOnly": true,
                    "type": ["string","null"],
                    "default": null
                  },
                  "name": {
                    "readOnly": true,
                    "type": ["string","null"],
                    "default": null
                  },
                  "id": {
                    "readOnly": true,
                    "type": ["integer","null"],
                    "default": null
                  },
                  "code": {
                    "readOnly": true,
                    "type": ["string","null"],
                    "default": null
                  }
                }
              },
              "geonames_admin2": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "ascii_name": {
                    "readOnly": true,
                    "type": ["string","null"],
                    "default": null
                  },
                  "name": {
                    "readOnly": true,
                    "type": ["string","null"],
                    "default": null
                  },
                  "id": {
                    "readOnly": true,
                    "type": ["integer","null"],
                    "default": null
                  },
                  "code": {
                    "readOnly": true,
                    "type": ["string","null"],
                    "default": null
                  }
                }
              },
              "nuts_level1": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "name": {
                    "type": [
                      "null",
                      "string"
                    ],
                    "default": null
                  },
                  "code": {
                    "type": [
                      "null",
                      "string"
                    ],
                    "default": null
                  }
                },
                "required": [
                  "code",
                  "name"
                ]
              },
              "nuts_level2": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "name": {
                    "type": [
                      "null",
                      "string"
                    ],
                    "default": null
                  },
                  "code": {
                    "type": [
                      "null",
                      "string"
                    ],
                    "default": null
                  }
                },
                "required": [
                  "code",
                  "name"
                ]
              },
              "nuts_level3": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "name": {
                    "type": [
                      "null",
                      "string"
                    ],
                    "default": null
                  },
                  "code": {
                    "type": [
                      "null",
                      "string"
                    ],
                    "default": null
                  }
                },
                "required": [
                  "code",
                  "name"
                ]
              }
            }
          },
          "lat": {
            "type": "number",
            "readOnly": true
          },
          "lng": {
            "type": "number",
            "readOnly": true
          },
          "city": {
            "type": "string",
            "readOnly": true
          },
          "state_code": {
            "type": [
              "null",
              "string"
            ],
            "readOnly": true,
            "default": null
          },
          "state": {
            "readOnly": true,
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          "country_geonames_id": {
            "type": "integer",
            "readOnly": true
          },
          "primary": {
            "type": "boolean",
            "default": false
          },
          "postcode": {
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          "line": {
            "type": [
              "null",
              "string"
            ],
            "default": null
          }
        }
      }
    },
    "types": {
      "type": "array",
      "description": "Institutional Types",
      "items": {
        "type": "string",
        "enum": [
          "Education",
          "Healthcare",
          "Company",
          "Archive",
          "Nonprofit",
          "Government",
          "Facility",
          "Other"
        ]
      }
    },
    "external_ids": {
      "type": "object",
      "default": {},
      "additionalProperties": true,
      "title": "External IDs",
      "properties": {
        "GRID": {
          "type": "object",
          "title": "GRID",
          "additionalProperties": false,
          "properties": {
            "preferred": {
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            "all": {
              "type": [
                "null",
                "string"
              ]
            }
          }
        },
        "ISNI": {
          "type": "object",
          "title": "ISNI",
          "additionalProperties": false,
          "properties": {
            "preferred": {
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            "all": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "FundRef": {
          "type": "object",
          "title": "FunderRef",
          "additionalProperties": false,
          "properties": {
            "preferred": {
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            "all": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "Wikidata": {
          "type": "object",
          "title": "Wikidata",
          "additionalProperties": false,
          "properties": {
            "preferred": {
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            "all": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "established": {
      "type": ["null", "number"],
      "default": null
    },
    "relationships": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "type": {
            "type": "string",
            "enum": ["Related", "Parent", "Child", "Successor", "Predecessor"]
          },
          "id": {
            "type": "string",
            "pattern": "^https://ror.org/0[a-z|0-9]{8}$"
          },
          "label": {
            "$ref": "#/definitions/non-empty-string"
          }
        },
        "required": ["id", "label", "type"]
      }
    },
    "email_address": {
      "type": ["null", "string"],
      "default": null
    },
    "id": {
      "type": "string",
      "pattern": "^https://ror.org/0[a-z|0-9]{8}$",
      "readOnly": true,
      "default": "https://ror.org/012xzy7a9"
    },
    "labels": {
      "type": "array",
      "default": [],
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string"
          },
          "iso639": {
            "type": "string",
            "minLength": 2,
            "maxLength": 2
          }
        },
        "required": ["label", "iso639"]
      }
    },
    "status": {
      "type": "string",
      "enum": ["active", "inactive", "withdrawn"],
      "readOnly": true,
      "default": "active"
    }
  },
  "definitions": {
    "non-empty-string": {
      "type": "string",
      "minLength": 1
    }
  },
  "required": ["name", "types", "addresses"]
}

=== ror-community/ror-schema/files/test.json
{
        "ip_addresses": [],
        "aliases": [],
        "acronyms": [
            "ANU"
        ],
        "links": [
            "http://www.anu.edu.au/"
        ],
        "country": {
            "country_code": "AU",
            "country_name": "Australia"
        },
        "name": "Australian National University",
        "wikipedia_url": "http://en.wikipedia.org/wiki/Australian_National_University",
        "addresses": [
            {
                "lat": -35.2778,
                "state_code": "AU-ACT",
                "country_geonames_id": 2077456,
                "lng": 149.1205,
                "state": "Australian Capital Territory",
                "city": "Canberra",
                "geonames_city": {
                    "nuts_level2": {
                        "name": null,
                        "code": null
                    },
                    "geonames_admin2": {
                        "ascii_name": null,
                        "id": null,
                        "name": null,
                        "code": null
                    },
                    "geonames_admin1": {
                        "ascii_name": "ACT",
                        "id": 2177478,
                        "name": "ACT",
                        "code": "AU.01"
                    },
                    "city": "Canberra",
                    "id": 2172517,
                    "nuts_level1": {
                        "name": null,
                        "code": null
                    },
                    "nuts_level3": {
                        "name": null,
                        "code": null
                    },
                    "license": {
                        "attribution": "Data from geonames.org under a CC-BY 3.0 license",
                        "license": "http://creativecommons.org/licenses/by/3.0/"
                    }
                },
                "postcode": null,
                "primary": false,
                "line": null
            }
        ],
        "types": [
            "Education"
        ],
        "established": 1946,
        "relationships": [
            {
                "type": "Related",
                "id": "https://ror.org/041c7s516",
                "label": "Calvary Hospital"
            },
            {
                "type": "Related",
                "id": "https://ror.org/04h7nbn38",
                "label": "Canberra Hospital"
            },
            {
                "type": "Related",
                "id": "https://ror.org/030jpqj15",
                "label": "Goulburn Base Hospital"
            },
            {
                "type": "Child",
                "id": "https://ror.org/006a4jj40",
                "label": "Mount Stromlo Observatory"
            }
        ],
        "email_address": null,
        "external_ids": {
            "GRID": {
                "all": "grid.1001.0",
                "preferred": "grid.1001.0"
            }
        },
        "id": "https://ror.org/019wvm592",
        "labels": [],
        "status": "active"
    }
